#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  cd "$shome"
  block compile pipenv
  mkdir -p "$shome/bin"
  ln -nfs "$(pipenv run which bin/cookiecutter)" "$shome/bin/"
}

main "$@"
