#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  block compile virtualenv
  mkdir -p "$shome/bin"
  ln -nfs ../vendor/virtualenv/bin/cookiecutter "$shome/bin/"
}

main "$@"
