#!/usr/bin/env bash

function version {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  local ver_cookiecutter="0.0.1"
  jq -n --arg cookiecutter "$ver_cookiecutter" '{cookiecutter: $cookiecutter}'
}

version "$@"
